# Generated by Django 5.1.5 on 2026-01-28 04:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("solicitudes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionRecordatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50, verbose_name="Tipo")),
                (
                    "ventana_horas",
                    models.PositiveIntegerField(verbose_name="Ventana (horas)"),
                ),
                (
                    "mensaje_template",
                    models.TextField(verbose_name="Template del Mensaje"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Configuración de Recordatorio",
                "verbose_name_plural": "Configuraciones de Recordatorio",
                "db_table": "configuracion_recordatorios",
            },
        ),
        migrations.CreateModel(
            name="TipoNotificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("proposito", models.TextField(verbose_name="Propósito")),
                (
                    "icono",
                    models.CharField(
                        default="bell", max_length=50, verbose_name="Icono"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="blue", max_length=20, verbose_name="Color"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Notificación",
                "verbose_name_plural": "Tipos de Notificación",
                "db_table": "tipos_notificacion",
            },
        ),
        migrations.CreateModel(
            name="PreferenciaNotificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_entrevistas",
                    models.BooleanField(default=True, verbose_name="Email Entrevistas"),
                ),
                (
                    "email_documentos",
                    models.BooleanField(default=True, verbose_name="Email Documentos"),
                ),
                (
                    "email_simulacros",
                    models.BooleanField(default=True, verbose_name="Email Simulacros"),
                ),
                (
                    "email_recordatorios",
                    models.BooleanField(
                        default=True, verbose_name="Email Recordatorios"
                    ),
                ),
                (
                    "push_habilitado",
                    models.BooleanField(default=False, verbose_name="Push Habilitado"),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias_notificacion",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia de Notificación",
                "verbose_name_plural": "Preferencias de Notificación",
                "db_table": "preferencias_notificacion",
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrevista_agendada", "Entrevista Agendada"),
                            ("entrevista_reprogramada", "Entrevista Reprogramada"),
                            ("entrevista_cancelada", "Entrevista Cancelada"),
                            ("recordatorio_entrevista", "Recordatorio de Entrevista"),
                            ("preparacion_recomendada", "Preparación Recomendada"),
                            ("simulacion_completada", "Simulación Completada"),
                            ("recomendaciones_listas", "Recomendaciones Listas"),
                            ("documento_aprobado", "Documento Aprobado"),
                            ("documento_rechazado", "Documento Rechazado"),
                            ("solicitud_aprobada", "Solicitud Aprobada"),
                            ("solicitud_rechazada", "Solicitud Rechazada"),
                            ("solicitud_enviada", "Solicitud Enviada a Embajada"),
                            ("simulacro_propuesto", "Simulacro Propuesto"),
                            ("simulacro_confirmado", "Simulacro Confirmado"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=50,
                        verbose_name="Tipo",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                ("detalle", models.TextField(blank=True, verbose_name="Detalle")),
                (
                    "datos",
                    models.JSONField(default=dict, verbose_name="Datos Adicionales"),
                ),
                ("leida", models.BooleanField(default=False, verbose_name="Leída")),
                (
                    "fecha_lectura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Lectura"
                    ),
                ),
                (
                    "url_accion",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="URL de Acción"
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="solicitudes.solicitud",
                        verbose_name="Solicitud",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "db_table": "notificaciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "leida"],
                        name="notificacio_usuario_ef49b7_idx",
                    ),
                    models.Index(
                        fields=["usuario", "tipo"],
                        name="notificacio_usuario_60ca59_idx",
                    ),
                ],
            },
        ),
    ]
