# Generated by Django 5.2.10 on 2026-02-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("solicitud_creada", "Solicitud Creada"),
                    ("solicitud_asignada", "Solicitud Asignada"),
                    ("solicitud_aprobada", "Solicitud Aprobada"),
                    ("solicitud_rechazada", "Solicitud Rechazada"),
                    ("solicitud_enviada", "Solicitud Enviada a Embajada"),
                    ("solicitud_en_revision", "Solicitud en Revisión"),
                    ("contrato_generado", "Contrato Generado"),
                    ("contrato_pendiente", "Contrato Pendiente de Firma"),
                    ("contrato_firmado", "Contrato Firmado"),
                    ("contrato_aprobado", "Contrato Aprobado"),
                    ("documento_subido", "Documento Subido"),
                    ("documento_aprobado", "Documento Aprobado"),
                    ("documento_rechazado", "Documento Rechazado"),
                    ("entrevista_agendada", "Entrevista Agendada"),
                    ("entrevista_reprogramada", "Entrevista Reprogramada"),
                    ("entrevista_cancelada", "Entrevista Cancelada"),
                    ("recordatorio_entrevista", "Recordatorio de Entrevista"),
                    ("preparacion_recomendada", "Preparación Recomendada"),
                    ("simulacro_propuesto", "Simulacro Propuesto"),
                    ("simulacro_confirmado", "Simulacro Confirmado"),
                    ("simulacion_completada", "Simulación Completada"),
                    ("recomendaciones_listas", "Recomendaciones Listas"),
                    ("general", "General"),
                    ("mensaje", "Mensaje"),
                ],
                db_index=True,
                default="general",
                max_length=50,
                verbose_name="Tipo",
            ),
        ),
    ]
