# Generated by Django 5.1.5 on 2026-01-28 00:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Eliminado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "tipo_visa",
                    models.CharField(
                        choices=[
                            ("vivienda", "Visa de Vivienda"),
                            ("trabajo", "Visa de Trabajo"),
                            ("estudio", "Visa de Estudio"),
                            ("turismo", "Visa de Turismo"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Visa",
                    ),
                ),
                (
                    "embajada",
                    models.CharField(
                        choices=[
                            ("usa", "Estados Unidos"),
                            ("brasil", "Brasil"),
                            ("canada", "Canadá"),
                            ("espana", "España"),
                        ],
                        max_length=20,
                        verbose_name="Embajada",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("pendiente", "Pendiente de Revisión"),
                            ("en_revision", "En Revisión"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                            ("enviada_embajada", "Enviada a Embajada"),
                            ("entrevista_agendada", "Entrevista Agendada"),
                            ("completada", "Completada"),
                        ],
                        db_index=True,
                        default="borrador",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "datos_personales",
                    models.JSONField(
                        default=dict,
                        help_text="Nombre, pasaporte, nacionalidad, etc.",
                        verbose_name="Datos Personales",
                    ),
                ),
                (
                    "documentos",
                    models.JSONField(
                        default=list,
                        help_text="Lista de documentos adjuntos",
                        verbose_name="Documentos",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "notas_asesor",
                    models.TextField(blank=True, verbose_name="Notas del Asesor"),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Asignación"
                    ),
                ),
                (
                    "fecha_revision",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Revisión"
                    ),
                ),
                (
                    "fecha_envio_embajada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Envío a Embajada"
                    ),
                ),
                (
                    "asesor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"rol": "asesor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_asignadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asesor Asignado",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        limit_choices_to={"rol": "cliente"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_como_cliente",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud",
                "verbose_name_plural": "Solicitudes",
                "db_table": "solicitudes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Entrevista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha de Entrevista")),
                ("hora", models.TimeField(verbose_name="Hora de Entrevista")),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de Agendar"),
                            ("agendada", "Agendada"),
                            ("confirmada", "Confirmada"),
                            ("reprogramada", "Reprogramada"),
                            ("cancelada", "Cancelada"),
                            ("completada", "Completada"),
                        ],
                        default="agendada",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "veces_reprogramada",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Veces Reprogramada"
                    ),
                ),
                (
                    "motivo_cancelacion",
                    models.TextField(blank=True, verbose_name="Motivo de Cancelación"),
                ),
                (
                    "solicitud",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrevista",
                        to="solicitudes.solicitud",
                        verbose_name="Solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrevista",
                "verbose_name_plural": "Entrevistas",
                "db_table": "entrevistas",
                "ordering": ["fecha", "hora"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "archivo",
                    models.FileField(
                        upload_to="solicitudes/documentos/%Y/%m/",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "motivo_rechazo",
                    models.TextField(blank=True, verbose_name="Motivo de Rechazo"),
                ),
                (
                    "fecha_revision",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Revisión"
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado por",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_adjuntos",
                        to="solicitudes.solicitud",
                        verbose_name="Solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "db_table": "documentos_solicitud",
            },
        ),
    ]
