# Generated by Django 5.1.5 on 2026-01-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitud",
            name="tipo_visa",
            field=models.CharField(
                choices=[
                    ("vivienda", "Visa de Vivienda"),
                    ("trabajo", "Visa de Trabajo"),
                    ("estudio", "Visa de Estudio"),
                ],
                max_length=20,
                verbose_name="Tipo de Visa",
            ),
        ),
    ]
