# Generated by Django 5.2.10 on 2026-02-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0003_solicitud_embassy_decision_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitud",
            name="fecha_asignacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Asignacion"
            ),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="fecha_envio_embajada",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Envio a Embajada"
            ),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="fecha_revision",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Revision"
            ),
        ),
    ]
