# Generated by Django 5.1.5 on 2026-01-28 04:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("solicitudes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Practica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "tipo_visa",
                    models.CharField(
                        choices=[
                            ("estudiante", "Visa de Estudiante"),
                            ("trabajo", "Visa de Trabajo"),
                            ("turismo", "Visa de Turismo"),
                            ("vivienda", "Visa de Vivienda"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Visa",
                    ),
                ),
                (
                    "total_preguntas",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Total Preguntas"
                    ),
                ),
                (
                    "respuestas_correctas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Respuestas Correctas"
                    ),
                ),
                (
                    "porcentaje",
                    models.PositiveIntegerField(default=0, verbose_name="Porcentaje"),
                ),
                (
                    "calificacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excelente", "Excelente"),
                            ("bueno", "Bueno"),
                            ("regular", "Regular"),
                            ("insuficiente", "Insuficiente"),
                        ],
                        max_length=20,
                        verbose_name="Calificación",
                    ),
                ),
                (
                    "respuestas",
                    models.JSONField(default=list, verbose_name="Respuestas"),
                ),
                (
                    "completado",
                    models.BooleanField(default=False, verbose_name="Completado"),
                ),
                (
                    "fecha_completado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Completado"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practicas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Práctica",
                "verbose_name_plural": "Prácticas",
                "db_table": "practicas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Simulacro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Eliminado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("hora", models.TimeField(verbose_name="Hora")),
                (
                    "modalidad",
                    models.CharField(
                        choices=[("virtual", "Virtual"), ("presencial", "Presencial")],
                        default="virtual",
                        max_length=20,
                        verbose_name="Modalidad",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("propuesto", "Propuesto"),
                            ("pendiente_respuesta", "Pendiente de Respuesta"),
                            ("contrapropuesta", "Contrapropuesta Pendiente"),
                            ("confirmado", "Confirmado"),
                            ("en_sala_espera", "En Sala de Espera"),
                            ("en_progreso", "En Progreso"),
                            ("completado", "Completado"),
                            ("cancelado", "Cancelado"),
                            ("no_asistio", "No Asistió"),
                        ],
                        db_index=True,
                        default="propuesto",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_propuesta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Propuesta"
                    ),
                ),
                (
                    "hora_propuesta",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora Propuesta"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inicio de Sesión"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de Sesión"
                    ),
                ),
                (
                    "duracion_minutos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Duración (minutos)"
                    ),
                ),
                (
                    "grabacion_activa",
                    models.BooleanField(default=False, verbose_name="Grabación Activa"),
                ),
                (
                    "url_grabacion",
                    models.URLField(blank=True, verbose_name="URL Grabación"),
                ),
                (
                    "transcripcion",
                    models.JSONField(default=list, verbose_name="Transcripción"),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "motivo_cancelacion",
                    models.TextField(blank=True, verbose_name="Motivo de Cancelación"),
                ),
                (
                    "asesor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"rol": "asesor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulacros_como_asesor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asesor",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        limit_choices_to={"rol": "cliente"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulacros_como_cliente",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulacros",
                        to="solicitudes.solicitud",
                        verbose_name="Solicitud Asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulacro",
                "verbose_name_plural": "Simulacros",
                "db_table": "simulacros",
                "ordering": ["-fecha", "-hora"],
            },
        ),
        migrations.CreateModel(
            name="Recomendacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "claridad",
                    models.CharField(
                        default="medio", max_length=20, verbose_name="Claridad"
                    ),
                ),
                (
                    "coherencia",
                    models.CharField(
                        default="medio", max_length=20, verbose_name="Coherencia"
                    ),
                ),
                (
                    "seguridad",
                    models.CharField(
                        default="medio", max_length=20, verbose_name="Seguridad"
                    ),
                ),
                (
                    "pertinencia",
                    models.CharField(
                        default="medio", max_length=20, verbose_name="Pertinencia"
                    ),
                ),
                (
                    "nivel_preparacion",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("alto", "Alto"),
                        ],
                        default="medio",
                        max_length=20,
                        verbose_name="Nivel de Preparación",
                    ),
                ),
                (
                    "fortalezas",
                    models.JSONField(default=list, verbose_name="Fortalezas"),
                ),
                (
                    "puntos_mejora",
                    models.JSONField(default=list, verbose_name="Puntos de Mejora"),
                ),
                (
                    "recomendaciones",
                    models.JSONField(default=list, verbose_name="Recomendaciones"),
                ),
                (
                    "accion_sugerida",
                    models.TextField(blank=True, verbose_name="Acción Sugerida"),
                ),
                (
                    "publicada",
                    models.BooleanField(default=False, verbose_name="Publicada"),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Generación"
                    ),
                ),
                (
                    "simulacro",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recomendacion",
                        to="preparacion.simulacro",
                        verbose_name="Simulacro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recomendación",
                "verbose_name_plural": "Recomendaciones",
                "db_table": "recomendaciones",
            },
        ),
    ]
