# Generated by Django 5.1.5 on 2026-01-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preparacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulacro",
            name="estado",
            field=models.CharField(
                choices=[
                    ("solicitado", "Solicitado"),
                    ("propuesto", "Propuesto"),
                    ("pendiente_respuesta", "Pendiente de Respuesta"),
                    ("contrapropuesta", "Contrapropuesta Pendiente"),
                    ("confirmado", "Confirmado"),
                    ("en_sala_espera", "En Sala de Espera"),
                    ("en_progreso", "En Progreso"),
                    ("completado", "Completado"),
                    ("cancelado", "Cancelado"),
                    ("no_asistio", "No Asistió"),
                ],
                db_index=True,
                default="propuesto",
                max_length=30,
                verbose_name="Estado",
            ),
        ),
    ]
