# Generated by Django 5.1.5 on 2026-01-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preparacion", "0003_alter_practica_tipo_visa"),
    ]

    operations = [
        migrations.AddField(
            model_name="recomendacion",
            name="analisis_raw",
            field=models.JSONField(
                default=dict,
                help_text="Respuesta completa de la IA",
                verbose_name="Análisis Raw IA",
            ),
        ),
        migrations.AddField(
            model_name="recomendacion",
            name="documento_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="recomendaciones/pdf/",
                verbose_name="Documento PDF",
            ),
        ),
        migrations.AddField(
            model_name="recomendacion",
            name="error_mensaje",
            field=models.TextField(blank=True, verbose_name="Mensaje de Error"),
        ),
        migrations.AddField(
            model_name="recomendacion",
            name="estado_feedback",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("generando", "Generando"),
                    ("generado", "Feedback generado"),
                    ("error", "Error en generación"),
                ],
                default="pendiente",
                max_length=20,
                verbose_name="Estado Feedback",
            ),
        ),
        migrations.AddField(
            model_name="recomendacion",
            name="fecha_publicacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Publicación"
            ),
        ),
        migrations.AddField(
            model_name="recomendacion",
            name="resumen_ejecutivo",
            field=models.TextField(blank=True, verbose_name="Resumen Ejecutivo"),
        ),
        migrations.AddField(
            model_name="simulacro",
            name="analisis_ia_completado",
            field=models.BooleanField(
                default=False, verbose_name="Análisis IA Completado"
            ),
        ),
        migrations.AddField(
            model_name="simulacro",
            name="analisis_ia_fecha",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha Análisis IA"
            ),
        ),
        migrations.AddField(
            model_name="simulacro",
            name="transcripcion_archivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="simulacros/transcripciones/",
                verbose_name="Archivo Transcripción",
            ),
        ),
        migrations.AddField(
            model_name="simulacro",
            name="transcripcion_texto",
            field=models.TextField(
                blank=True,
                help_text="Transcripción en texto plano para análisis de IA",
                verbose_name="Transcripción Texto",
            ),
        ),
        migrations.AlterField(
            model_name="recomendacion",
            name="claridad",
            field=models.CharField(
                default="medio", max_length=20, verbose_name="Claridad en respuestas"
            ),
        ),
        migrations.AlterField(
            model_name="recomendacion",
            name="coherencia",
            field=models.CharField(
                default="medio", max_length=20, verbose_name="Coherencia del discurso"
            ),
        ),
        migrations.AlterField(
            model_name="recomendacion",
            name="pertinencia",
            field=models.CharField(
                default="medio",
                max_length=20,
                verbose_name="Pertinencia de la información",
            ),
        ),
        migrations.AlterField(
            model_name="recomendacion",
            name="seguridad",
            field=models.CharField(
                default="medio", max_length=20, verbose_name="Seguridad al responder"
            ),
        ),
    ]
