# Generated by Django 5.1.5 on 2026-01-28 09:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preparacion", "0004_add_ia_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="Tu API key de Google AI Studio",
                        max_length=100,
                        verbose_name="API Key de Gemini",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        choices=[
                            ("gemini-2.5-pro", "Gemini 2.5 Pro (Mayor precisión)"),
                            ("gemini-2.5-flash", "Gemini 2.5 Flash (Más rápido)"),
                            ("gemini-2.0-flash", "Gemini 2.0 Flash"),
                            (
                                "gemini-2.5-flash-lite",
                                "Gemini 2.5 Flash Lite (Económico)",
                            ),
                        ],
                        default="gemini-2.5-flash",
                        help_text="Modelo de Gemini a utilizar",
                        max_length=50,
                        verbose_name="Modelo de IA",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, verbose_name="Configuración Activa"
                    ),
                ),
                (
                    "total_analisis",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Análisis Realizados"
                    ),
                ),
                (
                    "ultimo_uso",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Uso"
                    ),
                ),
                (
                    "asesor",
                    models.OneToOneField(
                        limit_choices_to={"rol__in": ["asesor", "admin"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_ia",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de IA",
                "verbose_name_plural": "Configuraciones de IA",
                "db_table": "configuracion_ia",
            },
        ),
    ]
