# Generated by Django 5.2.10 on 2026-02-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preparacion", "0006_simulacro_propuesto_por"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulacro",
            name="propuesto_por",
            field=models.CharField(
                choices=[("cliente", "Cliente"), ("asesor", "Asesor")],
                default="asesor",
                help_text="Indica quién inició la propuesta del simulacro",
                max_length=20,
                verbose_name="Propuesto Por",
            ),
        ),
    ]
